// src/shims/codegen.ts
import { helperNames } from "./runtime/index.js";
import { validateIdentifier, type ModuleShim, type ShimExport } from "./manifest.js";

const knownHelpers = new Set<string>(helperNames);

export function generateModuleShimSource(moduleShim: ModuleShim, helperModuleUrl: string): string {
  if (!moduleShim || typeof moduleShim.specifier !== "string") throw new Error("Invalid module shim manifest entry.");
  const lines = [
    "// <auto-generated by PiSharp.TsBridge codegen.ts>",
    `import { helpers } from ${JSON.stringify(helperModuleUrl)};`,
    "",
  ];
  for (const exportSpec of moduleShim.exports ?? []) lines.push(generateExport(exportSpec));
  return `${lines.join("\n")}\n`;
}

function generateExport(exportSpec: ShimExport): string {
  const name = validateIdentifier(exportSpec?.name, "export name");
  switch (exportSpec.kind) {
    case "helper":
      return `export const ${name} = ${helperReference(exportSpec.helper)};`;
    case "json-const":
      return `export const ${name} = ${JSON.stringify(exportSpec.value)};`;
    case "unavailable-function":
      return `export function ${name}() { throw new Error(${JSON.stringify(exportSpec.message ?? `${name} is not available inside the PiSharp TypeScript extension bridge.`)}); }`;
    case "async-unavailable-function":
      return `export async function ${name}() { throw new Error(${JSON.stringify(exportSpec.message ?? `${name} is not available inside the PiSharp TypeScript extension bridge.`)}); }`;
    case "runtime-function": {
      const runtimeAction = exportSpec.runtimeAction;
      if (typeof runtimeAction !== "string" || runtimeAction.length === 0)
        throw new Error(`Missing runtimeAction for runtime-function export '${name}'.`);
      return `export async function ${name}(...args) { const bridge = globalThis.__pisharpTsBridge; if (!bridge?.runtime) throw new Error(${JSON.stringify(`Runtime function '${name}' requires an active PiSharp TypeScript extension bridge runtime.`)}); const result = await bridge.runtime(${JSON.stringify(runtimeAction)}, { args }); if (result?.ok === false) throw new Error(result.error ?? ${JSON.stringify(`${name} failed.`)}); return result?.value ?? result; }`;
    }
    case "namespace":
      return `export const ${name} = {\n${(exportSpec.members ?? []).map((member) => `  ${validateIdentifier(member.name, "namespace member")}: ${memberExpression(member)},`).join("\n")}\n};`;
    default:
      throw new Error(`Unsupported shim export kind '${String((exportSpec as { kind?: unknown }).kind)}' for ${name}.`);
  }
}

function memberExpression(member: ShimExport): string {
  switch (member.kind) {
    case "helper":
      return helperReference(member.helper);
    case "json-const":
      return JSON.stringify(member.value);
    case "unavailable-function":
      return `function() { throw new Error(${JSON.stringify(member.message ?? `${member.name} is not available inside the PiSharp TypeScript extension bridge.`)}); }`;
    case "async-unavailable-function":
      return `async function() { throw new Error(${JSON.stringify(member.message ?? `${member.name} is not available inside the PiSharp TypeScript extension bridge.`)}); }`;
    case "runtime-function":
      throw new Error(`Namespace member '${member.name}' cannot use runtime-function kind; runtime-function exports must be top-level.`);
    default:
      throw new Error(`Unsupported namespace export kind '${String((member as { kind?: unknown }).kind)}' for ${member.name}.`);
  }
}

function helperReference(helper: string | null | undefined): string {
  const key = validateIdentifier(helper, "helper name");
  if (!knownHelpers.has(key)) throw new Error(`Unknown shim helper '${key}'.`);
  return `helpers.${key}`;
}
