<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <RootNamespace>PiSharp.Memory.Backends.Off</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PiSharp.Memory.Abstractions\PiSharp.Memory.Abstractions.csproj" />
    <ProjectReference Include="..\PiSharp.Extensions\PiSharp.Extensions.csproj" />
  </ItemGroup>

</Project>
