<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <RootNamespace>PiSharp.Browser</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PiSharp.Browser.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PiSharp.Extensions\PiSharp.Extensions.csproj" />
    <ProjectReference Include="..\PiSharp.Tools\PiSharp.Tools.csproj" />
    <PackageReference Include="Microsoft.Playwright" Version="1.51.0" />
  </ItemGroup>

</Project>
