<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <RootNamespace>PiSharp.Packages</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PiSharp.Cli.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PiSharp.Compatibility\PiSharp.Compatibility.csproj" />
  </ItemGroup>

</Project>
